### ISSUE TITLE
More flexible selection of ways

### ISSUE THREAD

**Issue by spth** [rovaniemi/osm-graph-parser#3]
From the documentation and source code, osm-graph-parser currently just imports all ways tagged as some type of highway.
I suggest to make osm-graph-parser more flexible, by allowing to specifying inclusion and exclusion lists of keys and key-value pairs as command line arguments

Use cases might be:

--include-ways highway for the current behaviour.
--include-ways highway --exclude-ways access=no,access=private for all highways accessible to the public
--include-ways railway --exclude-ways railway=abandoned to get all railway tracks

Philipp

**Comment by cxcorp** [comment]
Hey! Adding support for command line options is definitely a good idea. We'll be taking a look at further improvements next week so we'll keep you posted!
Thanks for the interest in the project!

@rovaniemi

**Comment by cxcorp** [comment]
I've implemented the functionality in #6. Your example filters could be used like this:

    java -jar osmparser.jar --includeWays highway --excludeWays access=no access=private
    java -jar osmparser.jar -i railway -e railway=abandoned

We still need to test the branch.
